<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Graviton.Tests</RootNamespace>
    <AssemblyName>Graviton.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../source/Graviton.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="6.0.0" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Playnite.SDK" Version="11.0.0-zeta10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

</Project>
